//rrd
import {
  FormProps,
  useNavigate,
  useOutletContext,
  useParams,
} from "react-router-dom";
//datatypes
import { AlertState, OutletContext } from "../datatypes/datatypes";
//bootstrap
import { Button, Col, Container, Form, Row } from "react-bootstrap";
import { useEffect, useState } from "react";
import {
  generateRandomId,
  getNoteById,
  saveUpdatedNotes,
} from "../utils/utils";
//components
import CustomAlert from "./CustomAlert";

const NoteForm = ({ action }: FormProps) => {
  //*Retrieve props
  const { notes, setNotes, currentNote, setCurrentNote } =
    useOutletContext<OutletContext>();

  //*retrieve params
  const { id } = useParams<{ id?: string }>();

  //*if action is "new" note, id is autogenerated and current note is updated.
  useEffect(() => {
    if (action === "new") {
      setCurrentNote({
        id: generateRandomId(),
        title: "",
        body: "",
      });
    }

    if (action === "edit") {
      const editNote = getNoteById(id!);
      setCurrentNote(editNote!);
    }
  }, []);

  //*onChange input handler
  const inputChangeHandler = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    setCurrentNote((prevNote) => ({
      ...prevNote,
      [e.target.name]: e.target.value,
    }));

    // Alert State default
    setAlertState({ on: false, message: "", type: "" });
  };

  //*navigate
  const navigate = useNavigate();

  //*onClick button handler
  const buttonClickHandler = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    if (action === "new") {
      saveUpdatedNotes([...notes, currentNote]);

      setAlertState({
        on: true,
        message: "Guardado Correctamente",
        type: "success",
      });
      setNotes((prevNotes) => [...prevNotes, currentNote]);

      //*set currentNote state to init
      setCurrentNote({
        id: generateRandomId(),
        title: "",
        body: "",
      });
    }

    if (action === "edit") {
      const updatedNotes = notes.map((note) =>
        note.id === currentNote.id ? currentNote : note
      );

      saveUpdatedNotes(updatedNotes);
      setNotes(updatedNotes);

      navigate("/notes");
    }
  };

  //* Alert State default
  const [alertState, setAlertState] = useState<AlertState>({
    on: false,
    message: "",
    type: "",
  });

  //*blank input
  const [isBlank, setIsBlank] = useState<boolean>(
    currentNote.title === "" && currentNote.body === ""
  );

  useEffect(() => {
    setIsBlank(currentNote.title === "" && currentNote.body === "");
  }, [currentNote]);

  return (
    <Container className="mt-2">
      <Row className="justify-content-center">
        <Col md={6}>
          {alertState.on && (
            <CustomAlert
              message={alertState.message}
              type={alertState.type}
              duration={3000}
            ></CustomAlert>
          )}
          <Form>
            <Form.Group controlId="formTitle">
              <Form.Label className="fw-bold">Titulo</Form.Label>
              <Form.Control
                type="text"
                placeholder="Titulo"
                value={currentNote.title}
                onChange={inputChangeHandler}
                name="title"
              />
            </Form.Group>
            <Form.Group controlId="formBody">
              <Form.Label className="fw-bold">Detalle</Form.Label>
              <Form.Control
                as="textarea"
                rows={5}
                placeholder="Detalle"
                value={currentNote.body}
                onChange={inputChangeHandler}
                name="body"
              />
            </Form.Group>
            {isBlank && (
              <p style={{ color: "red", fontStyle: "italic" }}>
                * Both inputs required for storage
              </p>
            )}
            <div className="text-center">
              <Button
                type="submit"
                variant="primary"
                className="mt-2 mx-auto"
                onClick={buttonClickHandler}
                disabled={isBlank}
              >
                {action === "new"
                  ? "Guardar Nuevo"
                  : action === "edit"
                  ? "Guardar Cambios"
                  : "indefinido"}
              </Button>
            </div>
          </Form>
        </Col>
      </Row>
    </Container>
  );
};

export default NoteForm;
